[project]
name = "Wordbook"
dynamic = ["version"]
requires-python = ">=3.12"
dependencies = [
    "wn>=0.11.0",
]

[tool.uv]
package = false

[tool.setuptools]
packages = ["wordbook"]

[tool.isort]
profile = "black"
line_length = 120

[tool.pylint.format]
max-line-length = 120

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120

[dependency-groups]
dev = [
    "pygobject-stubs>=2.12.0",
]
