on:
  push:
    branches: [main]
  pull_request:
name: CI
jobs:
  flatpak-builder:
    name: "Flatpak Builder"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: "wordbook-dev.flatpak"
        manifest-path: "build-aux/flatpak/dev.mufeed.Wordbook.Devel.json"
        run-tests: "true"